export const SHIPPING_PROVIDERS = [
    "4PX",
    "ABF Freight",
    "Accurate Freight Carrier",
    "Airpak Express",
    "Anjani Courier",
    "APC Postal Logistics",
    "Aramex Australia",
    "Aramex Courier",
    "ARC Carrier",
    "Asendia USA",
    "ATS Amazon Shipping",
    "Australia Post",
    "Better Trucks",
    "Border Express",
    "Bonds Courier",
    "Brazil Correios",
    "Blue Dart Courier",
    "Canada Post",
    "City-Link Express",
    "CMA CGM Container",
    "Con-way Freight",
    "Couriers Please",
    "Courier Post",
    "China Post",
    "CJ Packet",
    "Delhivery Courier",
    "Delex Courier",
    "Deutsche Post DHL",
    "DHL Active Tracing",
    "DHL Courier",
    "DHL Ecommerce Asia",
    "DHL Express",
    "DHL Express Piece ID",
    "DHL Global Forwarding",
    "DHL Global Mail",
    "Dicom Canada",
    "Dotzot Courier",
    "DPD Parcel",
    "DPD UK",
    "DPD US",
    "DSV Global",
    "DSV UAE",
    "DSV US",
    "DTDC",
    "DTDC Express Global PTE",
    "DTDC Australia",
    "DTDC Singapore",
    "DTDC UAE",
    "DTDC USA",
    "Echo",
    "Ecom Express Courier",
    "Ekart Logistics Courier",
    "FedEx India",
    "FedEx Courier",
    "FedEx Freight",
    "FedEx UK",
    "FedEx US",
    "FedEx Cross Border",
    "First Flight Courier",
    "Flyking Courier",
    "GarudaVega Courier",
    "Gati Courier",
    "Gati KWE Courier",
    "GDEX Courier",
    "GLS",
    "GLS Czech Republic",
    "GMS Worldwide Courier",
    "Gojavas Courier",
    "Hermes Germany",
    "Hermes World",
    "India Post Domestic",
    "India Post International",
    "Jaipur Golden",
    "Janco Ecommerce",
    "Japan Post",
    "JT Express Malaysia",
    "La Poste",
    "Lasership Courier",
    "Leopard Courier",
    "Lexship Courier",
    "Madhur Courier",
    "Mahindra Logistics",
    "Malaysia Post",
    "Maruti Courier",
    "Nandan Courier",
    "New Zealand Post",
    "NextSmartShip",
    "NITCO Roadways",
    "Nova Poshta International",
    "NuvoEx Courier",
    "Old Dominion",
    "Om Logistics",
    "OnTrac",
    "OSM Worldwide",
    "Overnite Courier",
    "Pickrr Courier",
    "Pitney Bowes",
    "Polar Express",
    "Pos Laju",
    "Poste Italiane",
    "Professional Courier",
    "Professional Courier Kuwait",
    "Professional Courier Singapore",
    "Professional Courier SriLanka",
    "Professional Courier UAE",
    "Professional Courier USA",
    "Procure Logistics",
    "Purolator",
    "Registered Post",
    "RL Carriers",
    "Roadrunner Freight",
    "Rivigo Courier",
    "Safexpress India Courier",
    "Safexpress Courier",
    "Sagawa Express",
    "Saia Freight",
    "Sameday",
    "Saudi Post",
    "SF Express",
    "Shadowfax",
    "Shiprocket",
    "Shree Anjani Courier",
    "Shree Mahavir Courier",
    "Shree Maruti Courier",
    "Shree Nandan Courier",
    "Shree Tirupati Courier",
    "Skyking Courier",
    "Skyman Air Express Courier",
    "SkyNet Worldwide Express",
    "SkyNet Worldwide Express Australia",
    "SkyNet Worldwide Express Germany",
    "SkyNet Worldwide Express India",
    "SkyNet Worldwide Express Malaysia",
    "SkyNet Worldwide Express Mexico",
    "SkyNet Worldwide Express Nigeria",
    "SkyNet Worldwide Express Pakistan",
    "SkyNet Worldwide Express Philippines",
    "SkyNet Worldwide Express Singapore",
    "SkyNet Worldwide Express UAE",
    "SkyNet Worldwide Express USA",
    "SkyNet Worldwide Express Yemen",
    "Spee-Dee Delivery",
    "Speed Post",
    "Spoton Courier",
    "SMSA Express",
    "ST Courier",
    "Swiss Post",
    "Sypost",
    "TCI Express Courier",
    "TCI Freight",
    "TCS Courier",
    "TCI XPS Courier",
    "Tirupati Courier",
    "TNT",
    "TNT Australia",
    "TNT Reference",
    "TNT UK",
    "Trackon Courier",
    "UPS",
    "USPS",
    "V-Xpress",
    "Vichare Courier",
    "VRL Logistics",
    "VTrans",
    "Winit",
    "XpressBees Logistics",
    "Yamato Japan",
    "YRC Freight",
    "YunExpress",
    "ZTO Express",
    "Zajel"
];
